name: NexusHub Pull and Push # Workflow name

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: self-hosted # Use Self-hosted as the runner 

    steps:
      - name: Pull and tag Docker image # Step to pull and tag Docker image
        run: |
          sudo docker pull yakirbartech/dockerhub:0.1
          sudo docker tag yakirbartech/dockerhub:0.1 75.101.216.72:9092/nexushub:0.1

      - name: Login to Nexus Hub # Step to login to Nexus Hub
        run: |
          sudo docker login 75.101.216.72:9092 \
            -u ${{ secrets.NEXUSHUB_USERNAME }} \
            -p ${{ secrets.NEXUSHUB_PASSWORD }}

      - name: Push Docker image # Step to push Docker image
        run: |
          sudo docker push 75.101.216.72:9092/nexushub:0.1

      - name: Logout from Nexus Hub # Step to logout from Nexus Hub
        run: sudo docker logout
